### ISSUE TITLE
Alpha ToDo's

### ISSUE THREAD

**Issue by lucaderosso** [lucaderosso/AV0#2]
- [x] device UI
- [x] update live set template
- [x] upload live set template
- [x] complete video
- [x] color video
- [x] visuals
- [x] identity
- [x] copy
- [x] upload video YT VM
- [x] add video to project page
