### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by lucaderosso** [lucaderosso/AV0#5]
**Performance**
- [ ] experient performing with live clips. consider also using performable for this.
- [ ] consider implementing animations linked to sustain — currently holding a pad just shows the shape
- [ ] improve arrangement of elements on the grid [make issue]
- [x] implement better distortion — current one is too aggressive on high freqs
- [x] bypass new scene sound from distorsions
- [x] map volume controls for top and bottom
- [x] some sounds, when hit by mistake, result invasive and odd
- [x] consider multiplying the value coming from audio in by those coming from a [cycle] to have ranges going from -1 to +1 and allowing a sort of LFO on for the distortion effect 
- [ ] [review pauses between scenes](https://github.com/lucaderosso/AV0/issues/8)
- [ ] [implement end state](https://github.com/lucaderosso/AV0/issues/6)
- [ ] make grid work also when subdivision is not a multiple of 4 or 8 [make issue]
- [x] noise-kick needs some LFO treatment for variations 
- [ ] crop sounds in samplers to reduce live file size
- [x] refine shapes
- [x] update setup-scene.maxpat to make simpler grids
- [ ] explore further performable sound manipulation: adsr etc.
- [ ] expand effects
- [ ] [list all existing variables that create a new scene](https://github.com/lucaderosso/AV0/issues/7) — choose which are necessary and define what needs to change

**PR**
- [ ] Export videos from Davinci
- [ ] Post video from Steim on IG
- [ ] ...
